#!/bin/sh

case $BLOCK_BUTTON in
	1) changemicvol mute ;;
  3) setsid -w -f "$TERMINAL" -c float-st -g 100x25 -e pulsemixer; pkill -RTMIN+12 dwmblocks && pkill -RTMIN+10 dwmblocks ;;
	4) changemicvol up1 ;;
	5) changemicvol down1 ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

vol="$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@)"

[ "$vol" != "${vol%\[MUTED\]}" ] && echo "[Muted]" && exit

vol="${vol#Volume: }"

split() {
	IFS=$2
	set -- $1
	printf '%s' "$@"
}

vol="$(printf "%.0f" "$(split "$vol" ".")")"

case 1 in
	$((vol >= 1)) ) icon="Mic:" ;;
	* ) echo "[Muted]" && exit ;;
esac

echo "[$icon$vol%]"
