#!/bin/sh

# Profile file, runs on login. Environmental variables are set here.
# ln to ~/.zprofile

# Add to $PATH
export PATH="$HOME/.local/bin:$PATH"

# Default programs:
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox"
export FMGR="thunar"

# Other program settings:
export GTK_USE_PORTAL="1"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"
export TMUX_CONFIG="$XDG_CONFIG_HOME/tmux/tmux.conf"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export MOZ_USE_XINPUT2="1" # Mozilla/librewolf smooth scrolling/touchpads.
export MOZ_ENABLE_WAYLAND="1"

# ZSH settings
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export ZPLUGDIR="$HOME/.local/src/zsh_plugins"

# Rofi todo script
export DONE_FILE=~/.rofi_todos_done

# Start graphical server on tty1 if not already running.
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx "$XINITRC"
  # Hyprland
fi
